name: adid_whatsup_version
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_blue: ^0.8.0
  auto_size_text: ^3.0.0
  geolocator: ^7.7.1
  flutter_map: ^0.14.0
  latlong: ^0.6.1
  rive: ^0.8.1
  torch_light: ^0.4.0
  perfect_volume_control: ^1.0.5
  audioplayers: ^0.20.1
  vibration: ^1.7.4-nullsafety.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:

 
  uses-material-design: true

  assets:
    - assets\ps1.png
    - assets\gps_ani.riv
    - assets/audio.mp3

